# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MockCode' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MockCode
  # platform :ios, '9.0'
  pod 'NearbyMessages'

  # target 'example' do
  
  # end


  target 'MockCodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MockCode-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MockCode-tvOS

  target 'MockCode-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
