# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MockCode' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MockCode
  platform :ios, '9.0'

  pod 'AppCenter/Crashes', '~> 1.5.0'
  pod 'AppCenter/Analytics', '~> 1.5.0'
  pod 'AppCenterReactNativeShared', '~> 1.4.0'
 
  pod 'NearbyMessages'

  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', path: '../node_modules/react-native', :subspecs => [
  'Core'
  ]

  # pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'react-native-webgl', :path => '../node_modules/react-native-webgl'

  # target 'example' do
  
  # end


  # target 'MockCodeTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end

# target 'MockCode-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for MockCode-tvOS

#   target 'MockCode-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     if target.name == "React"
#       target.remove_from_project
#     end
#   end
# end
